"""
Django REST Framework ViewSets & Serializers — Module 07 Code Snap
Install: pip install djangorestframework djangorestframework-simplejwt django-filter
Run:     python manage.py runserver
API:     http://localhost:8000/api/
Docs:    http://localhost:8000/api/ (DRF Browsable API)

NOTE: This is a reference file — copy relevant parts into your Django app.
"""

# ============================================================
# PART 1: Serializers (students/serializers.py)
# ============================================================

from rest_framework import serializers
# from .models import Student, Course  # uncomment in real file


class CourseSerializer(serializers.ModelSerializer):
    """Serializer for Course model"""
    student_count = serializers.IntegerField(read_only=True)
    total_revenue = serializers.SerializerMethodField()

    class Meta:
        # model = Course
        fields = [
            "id", "name", "duration_months", "fee",
            "is_active", "student_count", "total_revenue",
            "created_at",
        ]

    def get_total_revenue(self, obj):
        """Calculate total revenue from enrolled students"""
        count = getattr(obj, "student_count", 0)
        return float(obj.fee * count) if count else 0


class StudentListSerializer(serializers.ModelSerializer):
    """Lightweight serializer for list view (fewer fields)"""
    course_name = serializers.CharField(source="course.name", read_only=True)

    class Meta:
        # model = Student
        fields = ["id", "name", "email", "city", "course_name", "marks"]


class StudentDetailSerializer(serializers.ModelSerializer):
    """Full serializer for detail/create/update"""
    course_name = serializers.CharField(source="course.name", read_only=True)
    status = serializers.CharField(read_only=True)

    class Meta:
        # model = Student
        fields = [
            "id", "name", "email", "phone", "city", "gender",
            "course", "course_name", "marks", "status", "enrolled_on",
        ]
        read_only_fields = ["enrolled_on"]

    def validate_marks(self, value):
        if value < 0 or value > 100:
            raise serializers.ValidationError("Marks must be between 0 and 100")
        return value

    def validate_email(self, value):
        """Ensure email is unique (case-insensitive)"""
        value = value.lower().strip()
        qs = Student.objects.filter(email__iexact=value)
        if self.instance:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise serializers.ValidationError("A student with this email already exists.")
        return value


class StudentStatsSerializer(serializers.Serializer):
    """Serializer for stats endpoint (no model)"""
    total_students = serializers.IntegerField()
    average_marks = serializers.FloatField()
    pass_count = serializers.IntegerField()
    fail_count = serializers.IntegerField()
    city_distribution = serializers.DictField()


# ============================================================
# PART 2: ViewSets (students/views.py)
# ============================================================

from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from django.db.models import Avg, Count, Q


class StudentViewSet(viewsets.ModelViewSet):
    """
    CRUD API for Students at TechPath Institute.

    Endpoints (auto-generated by router):
      GET    /api/students/          — List all students (paginated)
      POST   /api/students/          — Create new student
      GET    /api/students/{id}/     — Get one student
      PUT    /api/students/{id}/     — Update student (full)
      PATCH  /api/students/{id}/     — Update student (partial)
      DELETE /api/students/{id}/     — Delete student

    Custom:
      GET    /api/students/stats/    — Aggregate stats
      GET    /api/students/toppers/  — Top 5 students
      POST   /api/students/bulk/     — Create multiple students
    """
    queryset = Student.objects.select_related("course").all()
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["course", "city", "gender"]
    search_fields = ["name", "email"]
    ordering_fields = ["name", "marks", "enrolled_on"]
    ordering = ["-enrolled_on"]

    def get_serializer_class(self):
        """Use lightweight serializer for list, full for detail"""
        if self.action == "list":
            return StudentListSerializer
        return StudentDetailSerializer

    def get_permissions(self):
        """Allow anyone to list/retrieve, require auth for create/update/delete"""
        if self.action in ["list", "retrieve", "stats", "toppers"]:
            return [AllowAny()]
        return [IsAuthenticated()]

    @action(detail=False, methods=["get"])
    def stats(self, request):
        """GET /api/students/stats/ — Aggregate statistics"""
        total = Student.objects.count()
        avg = Student.objects.aggregate(avg=Avg("marks"))["avg"] or 0
        pass_count = Student.objects.filter(marks__gte=40).count()

        city_dist = dict(
            Student.objects
            .values_list("city")
            .annotate(count=Count("id"))
            .order_by("-count")
        )

        data = {
            "total_students": total,
            "average_marks": round(avg, 1),
            "pass_count": pass_count,
            "fail_count": total - pass_count,
            "city_distribution": city_dist,
        }
        return Response(data)

    @action(detail=False, methods=["get"])
    def toppers(self, request):
        """GET /api/students/toppers/ — Top 5 by marks"""
        toppers = self.get_queryset().filter(marks__gte=75).order_by("-marks")[:5]
        serializer = StudentListSerializer(toppers, many=True)
        return Response(serializer.data)

    @action(detail=False, methods=["post"])
    def bulk(self, request):
        """POST /api/students/bulk/ — Create multiple students at once"""
        serializer = StudentDetailSerializer(data=request.data, many=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            {"created": len(serializer.data), "students": serializer.data},
            status=status.HTTP_201_CREATED,
        )


class CourseViewSet(viewsets.ModelViewSet):
    """
    CRUD API for Courses.

    Endpoints:
      GET    /api/courses/           — List all courses
      POST   /api/courses/           — Create course
      GET    /api/courses/{id}/      — Get course details
      PUT    /api/courses/{id}/      — Update course
      DELETE /api/courses/{id}/      — Delete course
    """
    queryset = Course.objects.annotate(student_count=Count("students"))
    serializer_class = CourseSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["name"]
    ordering_fields = ["name", "fee", "student_count"]
    ordering = ["name"]


# ============================================================
# PART 3: Router & URL Configuration (students/urls.py)
# ============================================================

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register("students", StudentViewSet, basename="student")
router.register("courses", CourseViewSet, basename="course")

# urlpatterns = router.urls
# Include in root urls.py:  path('api/', include('students.urls'))


# ============================================================
# PART 4: JWT Authentication Setup (mysite/urls.py)
# ============================================================

"""
# Add to mysite/urls.py:

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('students.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]


# Usage — get token:
# POST /api/token/  {"username": "admin", "password": "admin123"}
# Response: {"access": "eyJ...", "refresh": "eyJ..."}

# Use token:
# GET /api/students/  with header: Authorization: Bearer eyJ...
"""


# ============================================================
# PART 5: Pagination Configuration (settings.py snippet)
# ============================================================

"""
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '500/hour',
    },
}
"""


# ============================================================
# TESTING WITH CURL / HTTPIE
# ============================================================

"""
# List students
curl http://localhost:8000/api/students/

# Search
curl "http://localhost:8000/api/students/?search=rahul"

# Filter by city
curl "http://localhost:8000/api/students/?city=Bhopal"

# Create student (with JWT token)
curl -X POST http://localhost:8000/api/students/ \
  -H "Authorization: Bearer YOUR_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"name": "Kavya Mishra", "email": "kavya@email.com", "course": 1, "marks": 88, "city": "Bhopal"}'

# Get stats
curl http://localhost:8000/api/students/stats/

# Get toppers
curl http://localhost:8000/api/students/toppers/

# Using httpie (more readable):
# pip install httpie
http GET localhost:8000/api/students/ search==rahul
http POST localhost:8000/api/students/ name="Kavya" email="kavya@email.com" course=1 marks=88
"""
